# Generated by Django 5.0.3 on 2024-04-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=26)),
                ('num_of_travelers', models.CharField(max_length=3)),
                ('continent', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trip_type', models.CharField(max_length=30)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=5)),
                ('budge', models.CharField(max_length=20)),
                ('confirm_budge', models.BooleanField()),
                ('sub_for_contact', models.BooleanField()),
                ('sub_for_news', models.BooleanField(default=False)),
            ],
        ),
    ]
