# Generated by Django 5.0.3 on 2024-04-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquires',
            name='phone',
            field=models.CharField(max_length=26),
        ),
    ]
