# Generated by Django 5.0.3 on 2024-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_enquires_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquires',
            name='num_of_travelers',
            field=models.CharField(max_length=3),
        ),
    ]
