version: "3.7"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "firstclass"
      POSTGRES_USER: "postres"
      POSTGRES_PASSWORD: "postres"
    ports:
      - 8083:5432
    volumes:
      - db_data:/var/lib/postgresql/data:cached

volumes:
  db_data:
