.PHONY: run-server clean install migrate

run-server:
	@echo "Starting server..."
	@python manage.py runserver

migrate:
	@poetry run alembic upgrade head

install:
	@echo "Installing dep..."
	@poetry install
	@sudo apt-get update
	@poetry lock

clean:
	@echo "Removing lock..."
	@rm poetry.lock